# The documentation for the contents of this file can be found at:
# https://docs.gitlab.com/ce/ci/yaml/README.html

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
# The recipe for this docker image can be found at:
# https://github.com/rust-lang/docker-rust/blob/6314c6bc3d54d5b9284458c6a9061ef5766c9607/1.44.1/buster/Dockerfile
image: "rust:1.44.1"

stages:
  - build
  - test

build:cargo:
  stage: build
  artifacts:
    paths:
      - target/
  script:
  - rustc --version && cargo --version
  - cargo build --tests --all --verbose
  - cargo build --tests --all --verbose --release

lint:clippy:
  stage: test
  dependencies:
    - build:cargo
  script:
  - rustup component add clippy
  - cargo clippy --all-targets --all-features -- -D warnings
